### ISSUE TITLE
No indexed fields on events

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#1]
The `UniversalRaffleCore.sol` library contains event definitions with no indexed fields.  You may or may not want to index some of the fields so that user interfaces or other software can more easily find/search certain event information.

**Comment by illestrater** [comment]
Added some indexing for events: https://github.com/UniverseXYZ/RaffleContracts/commit/5ffdc072b38cd99fa5187670d35c481f29da6321

**Comment by mudgen** [comment]
Nice
