### ISSUE TITLE
Unnecessary State Read Within Inner Loop of calculatePaymentSplits function

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#10]
The `calculatePaymentSplits` function from `UniversalRaffleCore` library has this line of code which reads all the storage slots of a DepositedNFT struct within an inner loop:

```Solidity
 UniversalRaffleCore.DepositedNFT memory nft = raffle.slots[i].depositedNFTs[j];
```

However the `calculatePaymentSplits` function does not use every field of the DepositedNFT struct.  The `depositor` field which is not used is read from storage which costs 2,302 gas in every iteration of the inner loop according to my tests.

This can be fixed by changing "memory" to "storage" like this:
```Solidity
 UniversalRaffleCore.DepositedNFT storage nft = raffle.slots[i].depositedNFTs[j];
```

**Comment by illestrater** [comment]
Suggestion accepted: https://github.com/UniverseXYZ/RaffleContracts/commit/53e6be453c8719a530e0da86da196b7b9a9aea81

**Comment by mudgen** [comment]
Nice
