### ISSUE TITLE
IRoyaltiesProvider Implementation Partially Supports ERC2981 Royalties Standard

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#12]
The specification for the ERC2981 standard states that it supports dynamic royalties.  [From the standard](https://eips.ethereum.org/EIPS/eip-2981#specification):

> Subsequent invocations of royaltyInfo() MAY return a different royaltyAmount.

> The implementer MAY choose to change the percentage value based on other predictable variables that do not make assumptions about the unit of exchange. For example, the percentage value may drop linearly over time. 

The [current implementation of IRoyaltiesProvider caches](https://github.com/UniverseXYZ/Universe-Marketplace/blob/master/contracts/royalties/RoyaltiesRegistry.sol) the result of calling `royaltyInfo()` one time and thereafter uses a cached result. Therefore contract systems that use the current implementation of IRoyaltiesProvider do not support implementations of ERC2981 that may return a different royaltyAmount on subsequent invocations of royaltyInfo().

Specifically the IRoyaltiesProvider implementation would correctly calculate the secondary sales royalties for a tokenId the first time the tokenId was sold. But if the same tokenId was sold in another exchange or raffle then the cached secondary sales royalties value would be used instead of the current secondary sales royalty value if the token uses a dynamic implementation of ERC2981.

Note that the current implementation of IRoyaltiesProvider may calculate incorrect secondary sales royalties for ERC721 collections that use an implementation of ERC2981 that uses dynamic royalties.

**Comment by illestrater** [comment]
Although this affects Raffle contracts upon intended declared RoyaltiesProvider, not within scope of Raffle itself (and impacted issue already specified in: https://github.com/UniverseXYZ/RaffleContracts/issues/11)
