### ISSUE TITLE
IRoyaltiesProvider Definition Inconsistent Between Repos

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#13]
The `UniversalRaffleCore` library is using a version of `IRoyaltiesProvider` that is defined differently than the [Universe-Marketplace](https://github.com/UniverseXYZ/Universe-Marketplace/blob/master/contracts/interfaces/IRoyaltiesProvider.sol) repo.

This is the definition of `IRoyaltiesProvider` in the RaffleContracts repo:

https://github.com/UniverseXYZ/RaffleContracts/blob/4334ee7a44abbf04ee19e2c182c67123a60b596f/contracts/interfaces/IRoyaltiesProvider.sol#L1-L8

This is the definition of `IRoyaltiesProvider` in the Universe-Marketplace repo:

```Solidity
import "../lib/LibPart.sol";

interface IRoyaltiesProvider {
    function getRoyalties(address token, uint tokenId) external returns (LibPart.Part[] memory, LibPart.Part[] memory);
}
```

The return parameters are different.

Also, the version of [RoyaltiesRegistry](https://github.com/UniverseXYZ/RaffleContracts/blob/master/contracts/mock/MockRoyaltiesRegistry.sol) used in the RaffleContracts repo for testing is old. The more current and audited version was changed and is here: https://github.com/UniverseXYZ/Universe-Marketplace/blob/master/contracts/royalties/RoyaltiesRegistry.sol

**Comment by illestrater** [comment]
Royalties Registry updated with necessary contract code updates: https://github.com/UniverseXYZ/RaffleContracts/commit/6741b96509140559a215f114ce71ed9a084abc37

**Comment by mudgen** [comment]
Nice
