### ISSUE TITLE
Edge case changing `ds.royaltyFeeBps` can potentially mess up accounting

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#15]
The `finalizeRaffle` function in the UniversalRaffle contract is used to calculate and set state variables related to funds in a raffle. The `ds.royaltyFeeBps` state variable is used in some of these calculations.

The `distributeCapturedRaffleRevenue` function can be called after the `finalizeRaffle` function has executed.  The `distributeCapturedRaffleRevenue` also uses the `ds.royaltyFeeBps` state variable to make calculations related to sending funds.

The `finalizeRaffle` function and the `distributeCapturedRaffleRevenue` functions may depend on each other to use the same value for the `ds.royaltyFeeBps` state variable.

It is possible for the `ds.royaltyFeeBps` state variable to be changed after a `finalizeRaffle` transaction but before a `distributeCapturedRaffleRevenue` transaction. This can potentially cause `distributeCapturedRaffleRevenue` to revert when sending funds or cause funds to get stuck in the contract. Some testing may need to be done to verify the consequences.

**Comment by illestrater** [comment]
Great catch - stored the DAO royalty upon calculation so it's not calculated twice:
https://github.com/UniverseXYZ/RaffleContracts/commit/ab4462e1d061b44f8b45898e5c9c4b78a217b9ae

**Comment by mudgen** [comment]
Nice
