### ISSUE TITLE
`depositNFTsToRaffle` gas optimization

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#16]
The `depositNFTsToRaffle` function in the `UniversalRaffle` contract uses a loop to make multiple external function calls to the `depositERC721` function in the `UniversalRaffleCore` library.

Because of this gas is charged for repeated external function calls, and for repeatedly reading state variables to authenticate depositing into a raffle. Authentication to deposit NFTs into a raffles only needs to happen once, but it happens multiple times.

Generally it is more gas efficient not to make external function calls within a loop if you don't have to. The `depositNFTsToRaffle` function could be made more gas efficient by implementing the batch deposit functionality within a function in the `UniversalRaffleCore` library and calling it one time from the  `depositNFTsToRaffle` function.

**Comment by illestrater** [comment]
Suggestion accepted: https://github.com/UniverseXYZ/RaffleContracts/commit/6aeefa4ef023c7344ec19321170499c4298d7c61

**Comment by mudgen** [comment]
Nice
