### ISSUE TITLE
winners stored twice

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#17]
The winners of a raffle are stored twice as can be seen here:
https://github.com/UniverseXYZ/RaffleContracts/blob/4334ee7a44abbf04ee19e2c182c67123a60b596f/contracts/UniversalRaffle.sol#L191-L200

This is unnecessary and a significant gas issue because storing date is very expensive.

The winners can be stored once, using the `slots` mapping in the Raffle struct.

I recommend removing the `winners` mapping from the Raffle struct.

**Comment by illestrater** [comment]
Modified to storing token ID and winner address into slotInfo struct:

https://github.com/UniverseXYZ/RaffleContracts/commit/0cb9348b0a7055439a273f1356364855d3d92b18

**Comment by mudgen** [comment]
Nice
