### ISSUE TITLE
Gas Inefficient Functions

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#18]
It costs 2100 gas the first time a specific storage slot is read from contract storage. Subsequent reads to the same storage slot within the same transaction costs 100 gas. This is documented in the EIP here: https://eips.ethereum.org/EIPS/eip-2929 

In general and if possible smart contract code should not read storage slots that are never used because it costs gas with no benefit. Also storage slots should not be re-read within loops because it is far cheaper to read local variables and memory variables. More info on gas efficient code is here: https://eip2535diamonds.substack.com/p/smart-contract-gas-optimization-with?s=w

The `fulfillRandomWords` function from the `RandomNumberGenerator` contract is very gas inefficient because it reads multiple state variables that are never used. Specifically the function calls the `getRaffleConfig` function which reads multiple state variables that are not used. And it also calls the `getRaffleState` function which reads multiple state variable that are not used.

I suggest creating an external function that is called by the `fulfillRandomWords` function that only reads and returns the state variables that are used.

The `getWinners` function from the `RandomNumberGenerator` contract also reads state variables that are not used. From this line of code: `IUniversalRaffle(universalRaffleAddress).getRaffleConfig(raffleId).totalSlots`

**Comment by illestrater** [comment]
I've modified the functions slightly to directly pass only the used state variables into the function memory. I did not create separate external functions to provide these state variables in efforts not to exceed contract size: https://github.com/UniverseXYZ/RaffleContracts/commit/d6eff9f3c581d5bdaecce87c85dae3e20e63fb0e

**Comment by mudgen** [comment]
> I've modified the functions slightly to directly pass only the used state variables into the function memory.
In this case filling or not filling up memory variables is not the problem.  The problem is reading state variables in the [getRaffleState](https://github.com/UniverseXYZ/RaffleContracts/blob/64b5ea088d4361628d57a4b86bce260cd25a76ab/contracts/UniversalRaffleCore.sol#L595) function in the UniversalRaffleCore library.

I suggest making new functions that only read the state variables that are needed.

The contract size problem can be solved by creating and using a second Solidity library.

**Comment by illestrater** [comment]
Created a second library and only passing necessary memory data for VRF callback function: https://github.com/UniverseXYZ/RaffleContracts/commit/87196f7084065b310bdd8df8a6c05b66b7c37c18

**Comment by mudgen** [comment]
Nice
