### ISSUE TITLE
State Variables Already Initialized

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#2]
In the [configureRaffle](https://github.com/UniverseXYZ/RaffleContracts/blob/4334ee7a44abbf04ee19e2c182c67123a60b596f/contracts/UniversalRaffleCore.sol#L220) function the following state variables are initialized with values that they have by default:

https://github.com/UniverseXYZ/RaffleContracts/blob/4334ee7a44abbf04ee19e2c182c67123a60b596f/contracts/UniversalRaffleCore.sol#L247-L253

This would be fine and good for documentation purposes however these lines add 8,845 gas, according to my test.  If these lines are removed 8,845 gas is saved with no change to functionality.

**Comment by illestrater** [comment]
Resolved with this commit: https://github.com/UniverseXYZ/RaffleContracts/commit/274782b389e67954eeeeda2266fa778dda37bb07
