### ISSUE TITLE
random winners logic

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#20]
I found a few issues with this code from the `fulfillRandomWords` function from the https://github.com/UniverseXYZ/RaffleContracts/blob/master/contracts/RandomNumberGenerator.sol contract.

https://github.com/UniverseXYZ/RaffleContracts/blob/64b5ea088d4361628d57a4b86bce260cd25a76ab/contracts/RandomNumberGenerator.sol#L89-L107

### 1. Change uint32 to uint256
Using uint32 is more gas expensive than uint256.

### 2. It is possible for a `winnerId` value to match no existing ERC721 tokenId
This is how:

Let's say that ticketCounter == 200

Let's say that winnerIds[3] == 200

Now let's say that the next winnerId also equals 200.  This logic ` else winnerId++;` on line 98 will cause winnerId to become 201 which is not a valid token Id.  This can be fixed by changing `==` to `>=` in line 96: `if (((randomWords[i] % ticketCounter) + j + 1) == ticketCounter) {`

### 3. Lose randomness

The logic to change winnerId on line 97 `winnerId = (raffleId * 10000000) + 1; ` causes winners to be less random because this logic makes users with lower ticket numbers more likely to win raffles.  One idea to fix this is to hash randomWords[i] and use the result to get a different winnerId.

### 4. Duplicate Winners

It appears that the code above prevents duplicate winnerIds.  But duplicate winnerIds are still possible if a reset winnerId (from line 97 or 98) matches an earlier winnerId in the winnerIds array.

**Comment by illestrater** [comment]
Hey Nick - regarding 3. Lose randomness:

The logic is to prevent duplicate winners as you mentioned, but the logic increments the randomly picked ticket ID by one and checks to see if that ID is already picked - if not it will loop to keep incrementing.

I don't think this favors lower ticket numbers as line 97 is to reset the winner to the lowest ticket ID if the loop hits the max ticket count.

Could you double check my logic and reasoning to see if I'm making sense here?

Thanks man!

**Comment by mudgen** [comment]
@illestrater I rechecked it and you are right.  Randomness is not lost. I agree your reasoning makes sense.

**Comment by illestrater** [comment]
Great to hear thank you 👍

**Comment by illestrater** [comment]
Logic is still broken though haha - closed prematurely

**Comment by illestrater** [comment]
Fixed logic: https://github.com/UniverseXYZ/RaffleContracts/commit/87196f7084065b310bdd8df8a6c05b66b7c37c18

**Comment by mudgen** [comment]
Looks good now.
