### ISSUE TITLE
Efficient For Loops

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#4]
In some places in code in the `UniversalRaffleCore.sol` contract `uint32 i = 0` is used in for loops.
It is more gas efficient to use `uint256 i = 0` because 256 bits is the native type size of the EVM. It is only more gas efficient to use smaller types when they are read or written from storage and state variables are packed next to each other.

Here is a for loop used in the `setAllowList` function:
```Solidity
require(allowList.length <= 1000, 'Max 1000 per');
for (uint32 i = 0; i < allowList.length; i++) {
    raffle.allowList[allowList[i].participant] = allowList[i].allocation;
}
```

Here is a version of the same for loop that is optimized to save the most gas:
```Solidity
require(allowList.length <= 1000, 'Max 1000 per');
for (uint256 i; i < allowList.length;) {
    raffle.allowList[allowList[i].participant] = allowList[i].allocation;
    unchecked { i++; }
}
```

**Comment by illestrater** [comment]
Optimization with commit: https://github.com/UniverseXYZ/RaffleContracts/commit/24bac66045234fe9a38e2f2a11e998e8f4979d80

**Comment by mudgen** [comment]
Nice
