### ISSUE TITLE
Reading/Writing State Variables in Loops

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#5]
A general rule of gas efficiency is to not read or write state variables within loops if you don't have to.  Because reading and writing state variables is expensive.

The `_depositERC721` function from the `UniversalRaffleCore.sol` library is called within a loop. The function reads and writes these state variables that can be read and written once outside the `_depositERC721` function and outside the loop: 

* slot.depositedNFTCounter
* raffle.depositedNFTCounter

The code could be written:
```Solidity
uint256 nftSlotIndex = raffle.slots[slotIndex].depositedNFTCounter;
raffle.slots[slotIndex].depositedNFTCounter += tokens.length;
raffle.depositedNFTCounter += tokens.length;
uint256[] memory nftSlotIndexes = new uint256[](tokens.length);
for (uint256 i = 0; i < tokens.length; i += 1) {
   nftSlotIndex++;
   nftSlotIndexes[i] = nftSlotIndex;
    _depositERC721(
        raffleId,
        slotIndex,
        nftSlotIndex,
        tokens[i].tokenId,
        tokens[i].tokenAddress
    );
}
```

The `_withdrawDepositedERC721` function is also modifying state variables within a loop that could be set outside a loop.

The `claimERC721Rewards` function is also read/writings state variables within a loop that could be read/written outside the loop.

**Comment by illestrater** [comment]
Moved state variables read/write outside of loop: https://github.com/UniverseXYZ/RaffleContracts/commit/6ef81d1fd8f0e0e4822bccdc0aeb1c9b5a861aaf

**Comment by mudgen** [comment]
Nice
