### ISSUE TITLE
NFTs can be deposited in the 0 slot

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#6]
The `depositERC721` function in the `UniversalRaffleCore` library enables ERC721 tokens to be added to the `raffle.slots[0]`. I don't think this is intended because it enables someone to use one more slot than `raffleConfig.totalSlots`.

Specifically this require statement enables ERC721 tokens to be added to the 0 slot:
```Solidity
require((msg.sender == raffleConfig.raffler || raffle.depositors[msg.sender]) &&
            raffleConfig.totalSlots >= slotIndex && slotIndex >= 0 && (tokens.length <= 40) &&
            (raffle.slots[slotIndex].depositedNFTCounter + tokens.length <= ds.nftSlotLimit)
        , "E36");
```

It can be fixed by changing `slotIndex >= 0` to `slotIndex > 0`.

**Comment by illestrater** [comment]
Changed: https://github.com/UniverseXYZ/RaffleContracts/commit/c57f498eab023dd1d7bbf2ae5db031198098d9cb

**Comment by mudgen** [comment]
Nice
