### ISSUE TITLE
withdrawDepositedERC721 function code recommendation

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#7]
The function signature for the `withdrawDepositedERC721` function is this:
`function withdrawDepositedERC721(uint256 raffleId, uint256[][] calldata slotNftIndexes)`

It is not immediately clear how the `slotNftIndexes` parameter is supposed to work, and the parameter itself does not enforce that the arguments are used correctly. Each array in slotNftIndexes is supposed to contain a two element array, however it is possible for a user to put more elements in an array.

I suggest changing the `uint256[][] calldata slotNftIndexes` parameter to something like this:

```Solidity
struct SlotIndexAndNFTIndex {
    uint256 slotIndex;
    uint256 NFTIndex;
}

function withdrawDepositedERC721(uint256 raffleId, SlotIndexAndNFTIndex[] calldata slotsAndNFTIndexes)
```

**Comment by illestrater** [comment]
Suggestion implemented: https://github.com/UniverseXYZ/RaffleContracts/commit/e0f96f3bfe4db2cbd2c845845788b2fc4c6c2bdd

**Comment by mudgen** [comment]
Nice
