### ISSUE TITLE
claimERC721Rewards prevents transfer of NFTs with 0 tokenId

### ISSUE THREAD

**Issue by mudgen** [UniverseXYZ/RaffleContracts#8]
The `claimERC721Rewards` function from the `UniversalRaffleCore.sol` library prevents claiming ERC721 tokens with the tokenId of 0.

The tokenId 0 is a valid ERC721 tokenId and some ERC721 NFTs have the tokenId 0, for example this one: https://opensea.io/assets/0xa755a670aaf1fecef2bea56115e65e03f7722a79/0

I recommend removing the `if` condition in this code:
```Solidity
if (nftForWithdrawal.tokenId != 0) {
    IERC721(nftForWithdrawal.tokenAddress).safeTransferFrom(
        address(this),
        msg.sender,
        nftForWithdrawal.tokenId
    );
}
```

In addition the above `if` condition would increase state variables `raffle.withdrawnNFTCounter` and `raffle.slots[slotIndex].withdrawnNFTCounter` without withdrawing an NFT with the tokenId of 0.

**Comment by illestrater** [comment]
Great catch thank you, updated: https://github.com/UniverseXYZ/RaffleContracts/commit/dbc827c93263f58b457eb6df21394ba29fe7d483

**Comment by mudgen** [comment]
Nice
